#baseurl = "https://lecoding.com/"
languageCode = "zh-cn"
title = "乐Coding"
theme = "lecoding"
hasCJKLanguage = true

author = "Usbuild"
copyright = "&copy; 2020. All rights reserved."
canonifyurls = true
paginate = 10


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Archives"
    weight = 2
    identifier = "post"
    url = "/archives/"
  [[menu.main]]
    name = "Tags"
    weight = 3
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    weight = 4
    identifier = "about"
    url = "/about/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # CSS name for highlight.js
  highlightjs = "atelier-forest-light"
  dateFormat = "02 Jan 2006, 15:04" 
  googleAnalytics = "UA-19710645-12"
  wxqrpath = "https://open.weixin.qq.com/qr/code?username=gh_950f5a94ae02"
  pangu = true

[social]
  github = "usbuild"
  linkedin = "usbuild"

[markup.goldmark.renderer]
unsafe= true
