baseurl = "http://lecoding.com/"
languageCode = "zh-cn"
title = "乐Coding"
theme = "blackburn"
hasCJKLanguage = true

author = "Usbuild"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # CSS name for highlight.js
  highlightjs = "gruvbox-light"
  dateFormat = "02 Jan 2006, 15:04" 
  disqus = "lecoding"
  googleAnalytics = "UA-19710645-12"

[social]
  github = "usbuild"
  linkedin = "usbuild"
