baseurl = "https://lecoding.com/"
languageCode = "zh-cn"
title = "Usbuild's Blog"
theme = "lecoding"
hasCJKLanguage = true

author = "Usbuild"
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 10


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Archives"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Tags"
    weight = 3
    identifier = "tags"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    weight = 4
    identifier = "about"
    url = "/about/"

[indexes]
  tag = "tags"
  topic = "topics"
  
[params]
  # CSS name for highlight.js
  highlightjs = "gruvbox-light"
  dateFormat = "02 Jan 2006, 15:04" 
  disqus = "lecoding"
  author = "usbuild"
  googleAnalytics = "UA-19710645-12"

[social]
  github = "usbuild"
  linkedin = "usbuild"
