name = "lecoding"
license = "MIT"
licenselink = ""
description = "a simple blog theme"
homepage = "https://lecoding.com"
tags = ["blog", "personal", "purecss", "responsive"]
features = ["blog", "personal", "purecss", "responsive"]
min_version = 0.15

[author]
  name = "Usbuild"
  homepage = "https://lecoding.com"

# If porting an existing theme
[original]
  name = "Blackburn"
  homepage = "https://github.com/yoshiharuyamashita/blackburn"
  repo = "https://github.com/yoshiharuyamashita/blackburn"
